In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor
import os
import torch
import torchaudio
import parselmouth

In [2]:
files = pd.read_csv('nonAfrica.csv', header=0, index_col=0)

In [3]:
audios = {file:parselmouth.Sound('.././data/audios_development/'+file) for file in files['path']}

In [4]:
def computeF0(audio):
    pitch = audio.to_pitch()
    return pd.Series([pitch.selected_array['frequency'].mean(), 
            pitch.selected_array['frequency'].std(), 
            pitch.selected_array['frequency'].max(), 
            pitch.selected_array['frequency'][pitch.selected_array['frequency']>0].min()],
                     index=['meanF0', 'stdF0', 'maxF0', 'minF0'])

In [5]:
def computeSpectralCharacteristic(audio):
    spectrum = audio.to_spectrum() 
    # spectral_rolloff
    
    return pd.Series([spectrum.get_center_of_gravity(), spectrum.get_standard_deviation(), spectrum.get_skewness()],
                     index=['center_of_gravity', 'standard_deviation', 'skewness'])

In [6]:
def signalCharacteristics(audio):
    return pd.Series([audio.get_intensity(), audio.get_energy(), audio.get_energy_in_air(), audio.get_power(), audio.get_power_in_air()], 
                     index=['intensity', 'energy', 'energy_in_air', 'power', 'power_in_air'])

In [7]:
def computeRMSDuration(audio):
    return pd.Series([audio.get_root_mean_square(), audio.values.shape[1]/22050], index=['rms', 'duration'])

In [8]:
def getMFCC(audio):
    mfcc = audio.to_mfcc().extract_features().values[:-1, :]
    return pd.Series(np.concatenate([mfcc.mean(axis=1), mfcc.std(axis=1), mfcc.max(axis=1)], axis=0),
                     index=[f'mfcc_mean_{i}' for i in range(0, 3)]+[f'mfcc_std_{i}' for i in range(0, 3)]+[f'mfcc_max_{i}' for i in range(0, 3)])

In [9]:
def computeJitterShimmerHNR(key, files):
    return pd.Series(files[files['path']==key][['jitter', 'shimmer', 'hnr']].values[0], 
                     index=['jitter', 'shimmer', 'hnr'])

In [10]:
def computeZCR(audio):
    zcr = np.array([audio.get_nearest_zero_crossing(i) for i in range(0, audio.values.shape[1]//22050)])
    return pd.Series([zcr.mean(), zcr.std()], index=['zcrMean', 'zcrStd'])

In [26]:
from scipy.signal import stft

def compute_chroma(audio, sample_rate=22050, n_fft=2048, hop_length=512):
    # Calcola la STFT dello spettro
    _, _, Zxx = stft(audio, fs=sample_rate, nperseg=n_fft, noverlap=n_fft-hop_length)
    spectrogram = np.abs(Zxx)
    
    # Definisci il mappaggio delle frequenze alle note
    chroma_filter = np.zeros((12, n_fft // 2 + 1))
    frequencies = np.linspace(0, sample_rate // 2, n_fft // 2 + 1)
    A440 = 440.0  # Frequenza di riferimento
    
    for i, freq in enumerate(frequencies):
        if freq > 0:
            # Calcola il numero di semitoni rispetto al LA centrale (A440)
            note = int(np.round(12 * np.log2(freq / A440))) % 12
            chroma_filter[note, i] += 1
    
    # Applica il filtro alle frequenze e somma le energie per ciascuna banda
    chroma = np.dot(chroma_filter, spectrogram)
    chroma = chroma / (np.sum(chroma, axis=0, keepdims=True) +1e-12)
    return pd.Series(np.concatenate((chroma.mean(axis=1), chroma.std(axis=1), chroma.max(axis=1)), axis=0), 
            index=[f'chroma_mean_{i}' for i in range(12)] + [f'chroma_std_{i}' for i in range(12)] + [f'chroma_max_{i}' for i in range(12)])

In [12]:
def computeSilenceDuration(audio):
    dur = audio.total_duration
    audio = audio.values
    return pd.Series(audio[audio < audio.mean()-3*audio.std()].shape[0]/audio.shape[1]*dur, index=['silenceDuration'])

In [27]:
data = pd.concat([pd.DataFrame({file: pd.concat([
                                computeF0(audios[file]), 
                                computeSpectralCharacteristic(audios[file]),
                                # signalCharacteristics(audios[file]), 
                                # computeRMSDuration(audios[file]),
                                computeSilenceDuration(audios[file]),
                                getMFCC(audios[file]), 
                                computeJitterShimmerHNR(file, files),
                                computeZCR(audios[file]), 
                                compute_chroma(audios[file].values[0], 22050)]
                                  ) for file in audios}).T,
                        files.set_index(files['path'])['age']], axis=1)

In [28]:
# data = pd.read_csv('nonAfricaFeatures.csv', header=0, index_col=0)

In [33]:
data

,meanF0,stdF0,maxF0,minF0,center_of_gravity,standard_deviation,skewness,silenceDuration,mfcc_mean_0,mfcc_mean_1,...,chroma_max_3,chroma_max_4,chroma_max_5,chroma_max_6,chroma_max_7,chroma_max_8,chroma_max_9,chroma_max_10,chroma_max_11,age
1.wav,105.337970,121.841823,587.415757,78.107618,1125.768753,1213.670110,4.690098,0.492653,5943.947241,63.619388,...,0.568364,0.359980,0.495048,0.344745,0.372825,0.265705,0.273250,0.309603,0.252379,24.0
2.wav,107.219543,101.956515,416.290578,77.474473,476.688561,509.511523,5.272371,0.196100,8342.378031,67.863597,...,0.419268,0.317141,0.210184,0.173805,0.235624,0.333791,0.279595,0.426395,0.235092,22.5
3.wav,116.533228,119.920416,587.238408,93.960406,647.506469,1330.941691,5.533402,0.157324,6772.904887,69.078752,...,0.408443,0.364292,0.295528,0.168455,0.269057,0.674836,0.214311,0.312233,0.270297,22.0
4.wav,130.331735,109.496279,469.625117,85.656547,1013.801094,1862.988023,3.374334,0.126735,10316.574580,66.876994,...,0.422254,0.342949,0.414793,0.375782,0.332308,0.383218,0.417511,0.331221,0.246299,22.0
5.wav,60.492711,78.679495,597.502669,77.429089,608.678429,1098.335148,4.576950,0.287868,10881.592207,73.878072,...,0.391739,0.212762,0.320254,0.163460,0.223516,0.546847,0.388673,0.242281,0.218660,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2924.wav,90.350657,89.629836,578.264844,76.401820,534.117556,987.835844,7.606841,0.304422,8459.032375,69.423915,...,0.442970,0.265641,0.330319,0.212856,0.213289,0.485945,0.219229,0.382038,0.220884,27.0
2926.wav,102.840631,107.826812,550.534575,81.633244,610.067203,674.893843,5.910978,0.320437,1339.492388,47.177903,...,0.537602,0.409030,0.529391,0.533836,0.489730,0.279981,0.506623,0.483061,0.492954,22.0
2928.wav,100.281554,91.416195,562.003333,80.163402,653.714379,1219.474166,3.905207,0.542562,5456.890270,61.601533,...,0.248012,0.162988,0.328727,0.135851,0.295153,0.370609,0.262644,0.330186,0.249162,39.0
2929.wav,60.221861,66.950635,593.541250,75.313048,785.066539,1267.951417,3.155046,0.157959,12082.535236,70.757569,...,0.379535,0.229924,0.343581,0.192973,0.225624,0.577275,0.168529,0.241620,0.210686,24.0
2932.wav,86.151152,81.535227,491.776686,78.181892,507.586380,506.258733,5.849750,0.312245,8514.468091,64.659397,...,0.390711,0.306871,0.360523,0.132288,0.250109,0.268010,0.243336,0.309748,0.219141,18.0

In [34]:
temp = data.copy()
age = temp['age']
temp = temp.drop(columns=['age'])

In [35]:
temp = pd.DataFrame(StandardScaler().fit_transform(temp), columns=temp.columns, index=temp.index)

In [39]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1695 entries, 1.wav to 2932.wav
Data columns (total 58 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   meanF0              1695 non-null   float64
 1   stdF0               1695 non-null   float64
 2   maxF0               1695 non-null   float64
 3   minF0               1695 non-null   float64
 4   center_of_gravity   1695 non-null   float64
 5   standard_deviation  1695 non-null   float64
 6   skewness            1695 non-null   float64
 7   silenceDuration     1695 non-null   float64
 8   mfcc_mean_0         1695 non-null   float64
 9   mfcc_mean_1         1695 non-null   float64
 10  mfcc_mean_2         1695 non-null   float64
 11  mfcc_std_0          1695 non-null   float64
 12  mfcc_std_1          1695 non-null   float64
 13  mfcc_std_2          1695 non-null   float64
 14  mfcc_max_0          1695 non-null   float64
 15  mfcc_max_1          1695 non-null   float64
 16  mfcc_max_2          1695 non-null   float64
 17  jitter              1695 non-null   float64
 18  shimmer             1695 non-null   float64
 19  hnr                 1695 non-null   float64
 20  zcrMean             38 non-null     float64
 21  zcrStd              38 non-null     float64
 22  chroma_mean_0       1695 non-null   float64
 23  chroma_mean_1       1695 non-null   float64
 24  chroma_mean_2       1695 non-null   float64
 25  chroma_mean_3       1695 non-null   float64
 26  chroma_mean_4       1695 non-null   float64
 27  chroma_mean_5       1695 non-null   float64
 28  chroma_mean_6       1695 non-null   float64
 29  chroma_mean_7       1695 non-null   float64
 30  chroma_mean_8       1695 non-null   float64
 31  chroma_mean_9       1695 non-null   float64
 32  chroma_mean_10      1695 non-null   float64
 33  chroma_mean_11      1695 non-null   float64
 34  chroma_std_0        1695 non-null   float64
 35  chroma_std_1        1695 non-null   float64
 36  chroma_std_2        1695 non-null   float64
 37  chroma_std_3        1695 non-null   float64
 38  chroma_std_4        1695 non-null   float64
 39  chroma_std_5        1695 non-null   float64
 40  chroma_std_6        1695 non-null   float64
 41  chroma_std_7        1695 non-null   float64
 42  chroma_std_8        1695 non-null   float64
 43  chroma_std_9        1695 non-null   float64
 44  chroma_std_10       1695 non-null   float64
 45  chroma_std_11       1695 non-null   float64
 46  chroma_max_0        1695 non-null   float64
 47  chroma_max_1        1695 non-null   float64
 48  chroma_max_2        1695 non-null   float64
 49  chroma_max_3        1695 non-null   float64
 50  chroma_max_4        1695 non-null   float64
 51  chroma_max_5        1695 non-null   float64
 52  chroma_max_6        1695 non-null   float64
 53  chroma_max_7        1695 non-null   float64
 54  chroma_max_8        1695 non-null   float64
 55  chroma_max_9        1695 non-null   float64
 56  chroma_max_10       1695 non-null   float64
 57  chroma_max_11       1695 non-null   float64
dtypes: float64(58)
memory usage: 845.8+ KB

In [37]:
from sklearn.model_selection import KFold
from sklearn.pipeline import make_pipeline
from sklearn.decomposition import PCA 
pipeline = make_pipeline(StandardScaler(), 
                         PCA(n_components=40),
                         RandomForestRegressor(n_jobs=-1))

kf = KFold(n_splits=10, shuffle=True, random_state=42)

cross_val_score(pipeline, temp, age, cv=kf, scoring='neg_mean_absolute_error').mean()

ValueError:
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\pipeline.py", line 469, in fit
    Xt = self._fit(X, y, routed_params)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\pipeline.py", line 406, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\joblib\memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\pipeline.py", line 1310, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\decomposition\_pca.py", line 474, in fit_transform
    U, S, _, X, x_is_centered, xp = self._fit(X)
                                    ^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\decomposition\_pca.py", line 511, in _fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\utils\validation.py", line 1064, in check_array
    _assert_all_finite(
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\utils\validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\utente\OneDrive\Desktop\Magistrale\01TWZSM_DataScienceLab\.venv\Lib\site-packages\sklearn\utils\validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
PCA does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
clf = RandomForestRegressor(n_jobs=-1)
clf.fit(temp, data['age'])

for name, importance in sorted(zip(temp.columns, clf.feature_importances_), key=lambda x: x[1], reverse=True):
    print(f'{name}: {importance}')

zcrStd: 0.05280628640631185
zcrMean: 0.041750427124830576
silenceDuration: 0.037412870106319364
chroma_mean_9: 0.032824356762113746
mfcc_std_1: 0.02884744772862839
chroma_mean_5: 0.028621627553445342
minF0: 0.025355088989958613
mfcc_mean_1: 0.024301274399208688
jitter: 0.024056688577305967
chroma_mean_7: 0.024018563381955262
chroma_max_10: 0.020940531399127747
chroma_max_11: 0.02092524284238378
shimmer: 0.02024384685435543
chroma_std_4: 0.01933423479680965
chroma_std_5: 0.019089577114857606
chroma_max_3: 0.017997963682805672
chroma_max_1: 0.017793634002172595
mfcc_max_2: 0.017401601702770088
maxF0: 0.017057212139771454
chroma_max_2: 0.017012995125243995
chroma_mean_3: 0.016341046609289072
hnr: 0.016301487002438875
chroma_std_8: 0.016108372663062698
chroma_max_9: 0.0160988478318054
chroma_mean_0: 0.015928223386475125
mfcc_max_1: 0.015656523653694413
chroma_mean_4: 0.014923980934272822
chroma_max_8: 0.014465578467808257
chroma_mean_10: 0.014343065960640295
meanF0: 0.013768786840199212
chroma_std_9: 0.01367657999239131
chroma_max_0: 0.01364328519288604
chroma_mean_2: 0.013630519435746573
standard_deviation: 0.013616122939805641
stdF0: 0.0135501781777482
chroma_std_2: 0.013537193411958054
chroma_max_5: 0.013331718397943329
chroma_std_0: 0.013316608999350561
mfcc_max_0: 0.013310957369274321
chroma_std_10: 0.013154855789944766
mfcc_std_2: 0.01313783262951776
chroma_std_6: 0.012677344946065254
chroma_mean_1: 0.012645953142439385
chroma_std_1: 0.01261975995522272
chroma_mean_6: 0.012347995380892844
skewness: 0.012321177268389973
chroma_std_11: 0.012294200753810134
chroma_mean_11: 0.012174541962420744
chroma_max_4: 0.011954901764305437
mfcc_mean_2: 0.01106335305388859
chroma_max_7: 0.010849932041828556
chroma_std_7: 0.010623365505359547
mfcc_std_0: 0.01059782453654516
chroma_max_6: 0.010321788152878205
center_of_gravity: 0.010289770177459922
chroma_std_3: 0.010006504116513113
mfcc_mean_0: 0.009351368432599077
chroma_mean_8: 0.008226982432753006

In [ ]:
temptemp = pd.concat([temp.drop(columns=['chroma_std_0', 'chroma_std_1', 'chroma_std_2',
       'chroma_std_3', 'chroma_std_4', 'chroma_std_5', 'chroma_std_6',
       'chroma_std_7', 'chroma_std_8', 'chroma_std_9', 'chroma_std_10',
       'chroma_std_11',
       'chroma_max_0',  'chroma_max_1', 'chroma_max_2',
       'chroma_max_3', 'chroma_max_4', 'chroma_std_5', 'chroma_max_6',
       'chroma_max_7', 'chroma_max_8', 'chroma_std_9', 'chroma_max_10',
       'chroma_max_11',
       'mfcc_max_0', 'mfcc_max_1', 'mfcc_max_2']), 
                      pd.Series(temp[['chroma_std_0', 'chroma_std_1', 'chroma_std_2',
       'chroma_std_3', 'chroma_std_4', 'chroma_std_5', 'chroma_std_6',
       'chroma_std_7', 'chroma_std_8', 'chroma_std_9', 'chroma_std_10',
       'chroma_std_11']].mean(axis=1), name='chromaStd'),
                      pd.Series(temp[['chroma_max_0',  'chroma_max_1', 'chroma_max_2',
       'chroma_max_3', 'chroma_max_4', 'chroma_std_5', 'chroma_max_6',
       'chroma_max_7', 'chroma_max_8', 'chroma_std_9', 'chroma_max_10',
       'chroma_max_11']].mean(axis=1), name='chromaMax'),
                      pd.Series(temp[['mfcc_max_0', 'mfcc_max_1', 'mfcc_max_2']].mean(axis=1), name='mfccMax')], axis=1)
temptemp

            meanF0     stdF0     maxF0  ...  chromaStd  chromaMax   mfccMax
1.wav     0.820895  1.131923  0.573251  ...   0.435930   0.804674  0.393278
2.wav     0.886474  0.338809 -1.068385  ...   0.101751   0.041322 -0.580665
3.wav     1.211085  1.055289  0.571550  ...   0.266203   0.102061 -0.497320
4.wav     1.692006  0.639528 -0.556737  ...   0.873603   0.631780  1.273725
5.wav    -0.742102 -0.589582  0.670017  ...  -0.288833  -0.471509  0.824813
...            ...       ...       ...  ...        ...        ...       ...
2924.wav  0.298540 -0.152834  0.485465  ...   0.021234   0.028145 -0.416099
2926.wav  0.733855  0.572942  0.219443  ...   1.578920   1.664891 -1.857788
2928.wav  0.644663 -0.081586  0.329465  ...  -0.196686  -0.296150 -0.508757
2929.wav -0.751542 -1.057381  0.632015  ...  -0.533147  -0.595155  0.062971
2932.wav  0.152174 -0.475683 -0.344233  ...   0.245478  -0.058334  0.667340

[1695 rows x 36 columns]

In [ ]:
print(cross_val_score(RandomForestRegressor(n_jobs=-1), temptemp, 
                age, cv=10, scoring='neg_mean_absolute_error').mean())


for name, imp in sorted(zip(temptemp.columns, RandomForestRegressor(n_jobs=-1).fit(temptemp, age).feature_importances_), key=lambda x: x[1], reverse=True):
    print(f'{name}: {imp}')

-10.386645701357466
silenceDuration: 0.1016446150050201
chroma_mean_5: 0.06083756112584231
minF0: 0.05316411289294977
mfcc_std_1: 0.050586689501387526
mfcc_mean_1: 0.04615232425682087
chroma_mean_9: 0.03331680840652916
chroma_max_9: 0.03240356759362807
chroma_mean_3: 0.028907635470625883
hnr: 0.027639895408929086
chroma_mean_11: 0.02740701253001651
chroma_mean_4: 0.027406216811850643
shimmer: 0.027292910321297825
chroma_mean_7: 0.02643516967961849
jitter: 0.026420691635438538
chroma_mean_10: 0.026034814199931578
mfcc_mean_0: 0.02580719637577123
mfccMax: 0.024733064746728324
chroma_mean_0: 0.024548593807992607
chroma_mean_1: 0.024394278925667107
chroma_max_5: 0.023768927979044577
chroma_mean_2: 0.023714589678247296
chroma_mean_6: 0.023045883852698876
chroma_mean_8: 0.02276444287240745
maxF0: 0.02037628166362395
mfcc_std_2: 0.020313112316636527
standard_deviation: 0.019845369777072203
skewness: 0.019775938935696877
stdF0: 0.01915169415146857
mfcc_mean_2: 0.018560518528469516
mfcc_std_0: 0.018090294485644504
meanF0: 0.017832349326254694
center_of_gravity: 0.017700062291794126
chromaMax: 0.01736246396256833
chromaStd: 0.017285154240138524
zcrStd: 0.002997687108383091
zcrMean: 0.0022820701338053732

In [ ]:
cross_val_score(RandomForestRegressor(n_jobs=-1), files.drop(columns=['path', 'age', 'ethnicity']), files['age'], cv=10, scoring='neg_mean_absolute_error').mean()

np.float64(-10.838645144448313)

In [292]:
data

             meanF0       stdF0       maxF0  ...  chroma_max_10  chroma_max_11   age
1.wav     75.802961  117.835151  578.538578  ...       0.411964       0.340413  24.0
2.wav     72.628349   96.539640  277.558361  ...       0.668522       0.497765  22.5
3.wav     83.555433  113.581832  586.393148  ...       0.460150       0.401491  22.0
4.wav     99.814653  115.958678  592.696608  ...       0.323343       0.546532  22.0
5.wav     44.703150   87.716014  599.179923  ...       0.349590       0.313171  22.0
...             ...         ...         ...  ...            ...            ...   ...
2924.wav  66.384428   91.048773  595.946779  ...       0.413707       0.656444  27.0
2926.wav  89.040852  113.818455  572.075020  ...       0.442100       0.638669  22.0
2928.wav  70.308137   94.807730  598.577778  ...       0.395934       0.504553  39.0
2929.wav  38.332252   65.584079  545.277020  ...       0.367988       0.681643  24.0
2932.wav  70.243176   88.010649  598.756221  ...       0.297840       0.308565  18.0

[1695 rows x 59 columns]

In [358]:
totalData = pd.read_csv('.././data/development.csv', header=0, index_col=0).drop(columns=['sampling_rate'])
totalData['gender'] = totalData['gender'].map(lambda x: 0 if x=='male' else 1)
totalData['tempo'] = totalData['tempo'].map(lambda x: float(x[1:-1]))
evaluate = pd.read_csv('.././data/evaluation.csv', header=0, index_col=0).drop(columns=['sampling_rate'])
evaluate['path'] = evaluate['path'].map(lambda x: x.split('/')[-1])
evaluate['gender'] = evaluate['gender'].map(lambda x: 0 if x=='male'else 1)
evaluate['tempo'] = evaluate['tempo'].map(lambda x: float(x[1:-1]))

In [332]:
pd.Series(RandomForestRegressor(n_jobs=-1).fit(totalData.drop(columns=['age', 'ethnicity', 'path']), totalData['age'])
          .predict(evaluate.drop(columns=['ethnicity', 'path'])),
            index=evaluate.index, name='Predicted').to_csv('prediction.csv')

In [339]:
predictedAfrican = pd.Series(RandomForestRegressor(n_jobs=-1)
                    .fit(totalData[totalData['num_characters'] < 69].drop(columns=['path', 'ethnicity', 'age']), 
                         totalData[totalData['num_characters'] < 69]['age'])
                    .predict(evaluate[evaluate['num_characters'] < 69].drop(columns=['path', 'ethnicity'])),
                    index=evaluate[evaluate['num_characters'] < 69].index, name='Predicted')

In [341]:
predicted = pd.read_csv('prediction.csv', header=0, index_col=0)

In [344]:
for index in predicted.index:
    if index in predictedAfrican.index:
        predicted.loc[index] = predictedAfrican.loc[index]

In [ ]:
toVal = {item:parselmouth.Sound('.././data/audios_evaluation/'+item) for item in set(evaluate['path']).difference(set(predictedAfrican.index))}

In [360]:
dataVal = pd.concat([pd.DataFrame({file: pd.concat([
                                computeF0(toVal[file]), 
                                computeSpectralCharacteristic(toVal[file]),
                                # signalCharacteristics(toVal[file]), 
                                # computeRMSDuration(toVal[file]),
                                computeSilenceDuration(toVal[file]),
                                getMFCC(toVal[file]), 
                                computeJitterShimmerHNR(file, evaluate),
                                computeZCR(toVal[file]), 
                                compute_chroma(toVal[file].values[0], 22050)]
                                  ) for file in toVal}).T,
                        files.set_index(files['path'])['age']], axis=1)

C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione
C:\Users\utente\AppData\Local\Temp\ipykernel_42840\3502006958.py:22: RuntimeWarning: invalid value encountered in divide
  chroma = chroma / np.sum(chroma, axis=0, keepdims=True)  # Normalizzazione

KeyboardInterrupt:

In [ ]:
dataVal2 = pd.concat([dataVal.drop(columns=['chroma_std_0', 'chroma_std_1', 'chroma_std_2',
       'chroma_std_3', 'chroma_std_4', 'chroma_std_5', 'chroma_std_6',
       'chroma_std_7', 'chroma_std_8', 'chroma_std_9', 'chroma_std_10',
       'chroma_std_11',
       'chroma_max_0',  'chroma_max_1', 'chroma_max_2',
       'chroma_max_3', 'chroma_max_4', 'chroma_std_5', 'chroma_max_6',
       'chroma_max_7', 'chroma_max_8', 'chroma_std_9', 'chroma_max_10',
       'chroma_max_11',
       'mfcc_max_0', 'mfcc_max_1', 'mfcc_max_2']), 
                      pd.Series(dataVal[['chroma_std_0', 'chroma_std_1', 'chroma_std_2',
       'chroma_std_3', 'chroma_std_4', 'chroma_std_5', 'chroma_std_6',
       'chroma_std_7', 'chroma_std_8', 'chroma_std_9', 'chroma_std_10',
       'chroma_std_11']].mean(axis=1), name='chromaStd'),
                      pd.Series(dataVal[['chroma_max_0',  'chroma_max_1', 'chroma_max_2',
       'chroma_max_3', 'chroma_max_4', 'chroma_std_5', 'chroma_max_6',
       'chroma_max_7', 'chroma_max_8', 'chroma_std_9', 'chroma_max_10',
       'chroma_max_11']].mean(axis=1), name='chromaMax'),
                      pd.Series(dataVal[['mfcc_max_0', 'mfcc_max_1', 'mfcc_max_2']].mean(axis=1), name='mfccMax')], axis=1)
dataVal2