In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
import librosa
import parselmouth

In [2]:
nonAfricanCsv = pd.read_csv('./data/nonAfrica.csv', header=0, index_col=0)

In [3]:
nonAfricanAudio = {file:librosa.load('./data/audios_development/'+file)[0] for file in nonAfricanCsv['path'].apply(lambda x: x.split('/')[-1])}

In [4]:
def computeZcr(audio):
    zcr = librosa.feature.zero_crossing_rate(audio)
    return pd.Series([zcr.mean(), zcr.std(), zcr.max(), zcr.min()], index=['zcr_mean', 'zcr_std', 'zcr_max', 'zcr_min'])

In [5]:
def computeRMS(audio):
    rms = librosa.feature.rms(y=audio)
    return pd.Series([rms.mean(), rms.std(), rms.max(), rms.min()], index=['rms_mean', 'rms_std', 'rms_max', 'rms_min'])

In [6]:
def computeMFCC(audio):
    mfcc = librosa.feature.mfcc(y=audio, sr=22050, n_mfcc=13)
    return pd.Series(np.concatenate([mfcc.mean(axis=1), mfcc.std(axis=1), mfcc.max(axis=1), mfcc.min(axis=1)], axis=0), 
                                    index=np.array([[f'mfcc_mean{i}', f'mfcc_std{i}', f'mfcc_max{i}', f'mfcc_min{i}'] for i in range(0,13)]).T.flatten())

In [7]:
def computeF0(audio):
    f0 = librosa.yin(audio, fmin=100, fmax=2000)
    return pd.Series([f0.mean(), f0.std(), f0.max(), f0.min()], index=['f0_mean', 'f0_std', 'f0_max', 'f0_min'])

In [8]:
def computeSpectralFeature(audio):
    spectralCentroid = librosa.feature.spectral_centroid(y=audio)
    spectralBandwidth = librosa.feature.spectral_bandwidth(y=audio)
    spectralContrast = librosa.feature.spectral_contrast(y=audio)
    spectralRolloff = librosa.feature.spectral_rolloff(y=audio)
    return pd.Series([spectralCentroid.mean(), spectralCentroid.std(), spectralBandwidth.mean(), spectralBandwidth.std(), 
                      spectralContrast.mean(), spectralContrast.std(), spectralRolloff.mean(), spectralRolloff.std()],
                     index=['spectralCentroid_mean', 'spectralCentroid_std', 'spectralBandwidth_mean', 'spectralBandwidth_std',
                            'spectralContrast_mean', 'spectralContrast_std', 'spectralRolloff_mean', 'spectralRolloff_std'])

In [9]:
def computeSpeechRate(audio):
    intervals = librosa.effects.split(audio, top_db=20)    
    return pd.Series([np.sum(np.diff(intervals, axis=1))/audio.shape[0]], index=['speech_rate'])

In [10]:
def computePauses(audio):
    intervals = librosa.effects.split(audio, top_db=20)
    # Calculate the duration of pauses
    pause_durations = np.diff(intervals, axis=1) / 22050
    return pd.Series([intervals.shape[0], pause_durations.mean(), pause_durations.std()], 
                     index=['#pauses', 'mean_pause_duration', 'std_pause_duration'])

In [11]:
def computeJitterShimmerHNR(audio):
    jitter, shimmer = librosa.effects.jitter(audio), librosa.effects.shimmer(audio)
    HNR = librosa.effects.harmonic(audio)
    return pd.Series([jitter.mean(), jitter.std(), shimmer.mean(), shimmer.std(), HNR.mean(), HNR.std()], 
                     index=['jitter_mean', 'jitter_std', 'shimmer_mean', 'shimmer_std', 'HNR_mean', 'HNR_std'])

In [12]:
def computeFormantFeatures(audio, sr=22050):
    sound = parselmouth.Sound(audio, sr)
    formant = sound.to_formant_burg()
    
    f1 = formant.get_value_at_time(1, 0.5)
    f2 = formant.get_value_at_time(2, 0.5)
    f3 = formant.get_value_at_time(3, 0.5)
    
    b1 = formant.get_bandwidth_at_time(1, 0.5)
    b2 = formant.get_bandwidth_at_time(2, 0.5)
    b3 = formant.get_bandwidth_at_time(3, 0.5)
    
    total_energy = np.sum(audio ** 2)
    formant_energy = np.sum([f1, f2, f3])
    formant_energy_ratio = formant_energy / total_energy
    
    return pd.Series([f1, f2, f3, b1, b2, b3, formant_energy_ratio], 
                     index=['f1', 'f2', 'f3', 'b1', 'b2', 'b3', 'formant_energy_ratio'])

In [13]:
def computeChroma(audio):
    chroma = librosa.feature.chroma_stft(y=audio, sr=22050)
    return pd.Series(np.concatenate((chroma.mean(axis=1), chroma.std(axis=1)), axis=0),
                     index=np.array([[f'chroma_mean{i}', f'chroma_std{i}'] for i in range(0,12)]).T.flatten())

In [14]:
def computeTempo(audio):
    return pd.Series(librosa.feature.tempo(y=audio)[0], index=['tempo'])

In [15]:
def computeTonnetz(audio):
    tonnetto = librosa.feature.tonnetz(y=audio)
    return pd.Series(np.concatenate((tonnetto.mean(axis=1), tonnetto.std(axis=1)), axis=0),
                     index=np.array([[f'tonnetz_mean{i}', f'tonnetz_std{i}'] for i in range(0,6)]).T.flatten())

In [16]:
def computeMel(audio):
    mel = librosa.feature.melspectrogram(y=audio)
    return pd.Series(np.concatenate((mel.mean(axis=1), mel.std(axis=1)), axis=0),
                        index=np.array([[f'mel_mean{i}', f'mel_std{i}'] for i in range(0,128)]).T.flatten())

In [17]:
data = pd.DataFrame({file:pd.concat([
    computeZcr(nonAfricanAudio[file]),
    computeRMS(nonAfricanAudio[file]),
    computeMFCC(nonAfricanAudio[file]),
    computeF0(nonAfricanAudio[file]),
    computeSpectralFeature(nonAfricanAudio[file]),
    computeSpeechRate(nonAfricanAudio[file]),
    computePauses(nonAfricanAudio[file]),
    # computeJitterShimmerHNR(nonAfricanAudio[file]),
    computeFormantFeatures(nonAfricanAudio[file]),
    computeChroma(nonAfricanAudio[file]),
    computeTempo(nonAfricanAudio[file]),
    computeTonnetz(nonAfricanAudio[file]),
    computeMel(nonAfricanAudio[file])
    ], axis=0)
    for file in nonAfricanAudio}).T

In [18]:
data = pd.concat([data, nonAfricanCsv.set_index(nonAfricanCsv['path'])['age']], axis=1)

In [19]:
# data = pd.read_csv('./data/nonAfricanFeatures.csv', header=0, index_col=0)

In [20]:
corrrr = data.corr('spearman')['age']

for index in corrrr.map(np.abs).sort_values(ascending=False).index:
    print(index, corrrr[index])

age 1.0
mel_std126 -0.25428348999767864
mel_std125 -0.2520147920041821
mel_mean126 -0.251312529604878
mel_std127 -0.24979532639366184
#pauses 0.2484159248010522
mel_mean125 -0.2476288290569373
mel_mean127 -0.24628000848649068
mel_mean118 -0.24140459822211685
mel_std124 -0.2404358817326488
mel_mean119 -0.24032420695539616
mel_std122 -0.2396943900138066
mel_std119 -0.23891835178510681
mel_mean121 -0.23820112979395075
mel_std121 -0.2378891372907427
mel_std123 -0.2378002613112265
mel_mean120 -0.23746323710656128
mel_mean122 -0.23709651811823462
mel_mean124 -0.23650555444116675
mel_std118 -0.23563986839544152
mel_mean117 -0.2355278286598778
mel_std120 -0.23540263686247567
mel_mean123 -0.2352641092911123
mel_std117 -0.2290714855721846
mel_mean116 -0.2181941398404822
mel_std116 -0.21042061165648226
speech_rate -0.20732918148565674
spectralContrast_std 0.20072218113988202
mel_mean115 -0.19893906757706664
mel_std0 -0.1959229707185511
spectralCentroid_std -0.1954352446237269
mel_std115 -0.19087650350740532
mfcc_min6 -0.18510545225755143
mel_mean0 -0.1846643027342102
f0_mean -0.18373864392764472
spectralBandwidth_mean -0.1818049172483136
f0_std -0.1790296706816929
mel_std1 -0.1785719241859689
mel_mean114 -0.17549847832095752
mfcc_mean6 -0.17373050929508424
spectralCentroid_mean -0.17154041419783422
spectralRolloff_mean -0.16919379760492437
mfcc_min1 0.1681636958962548
mel_mean13 0.16706184801102472
mfcc_max2 -0.16623745034017373
mel_std114 -0.16609517948018737
mel_std14 0.1659262457030494
mel_std13 0.1632530937580158
mfcc_max6 -0.15954865223470752
mel_mean1 -0.15833048427368912
spectralRolloff_std -0.1565935798581111
spectralContrast_mean 0.15628590027440348
mel_mean12 0.15587282366230842
zcr_max -0.15137631382533306
mfcc_mean4 -0.14992466334982726
mfcc_mean1 0.14961709966504275
mel_mean14 0.14897080041702626
mfcc_min9 -0.14685272302831692
mfcc_mean11 -0.14676493813436423
mel_std12 0.1442089279434457
mel_mean113 -0.1420079075232417
mfcc_mean9 -0.1375017179377795
mfcc_std6 0.13749507101124242
zcr_std -0.13533442657013495
mel_std113 -0.13357645690879807
mfcc_std2 -0.13147136750681276
mfcc_max0 -0.13091018492111503
mel_std2 -0.13046037996755858
spectralBandwidth_std -0.12972962616064576
chroma_mean9 -0.12752917907022096
mel_mean34 -0.12542181607659506
mfcc_max4 -0.12524554367828317
mfcc_std1 -0.12498460958257408
mfcc_min11 -0.12493119497462767
mel_std15 0.12424664045121407
mel_mean5 0.12417917001642242
mel_mean39 -0.12293317151825048
chroma_mean5 0.12171530933311434
mel_std39 -0.12043369287652965
mel_mean35 -0.12036847014106597
chroma_mean4 0.11908384277841498
mel_std34 -0.11898301811311304
mel_mean55 -0.11655869869006168
mel_mean49 -0.11641893075362757
mean_pause_duration -0.1161775027677642
mel_mean36 -0.11494039709481026
mel_mean60 -0.11212339979059016
mel_std36 -0.11175009922299158
mel_mean58 -0.11153857505754529
mel_std35 -0.11111667831808023
mel_mean38 -0.11104222189075304
mel_mean6 0.11087042023175174
mel_mean59 -0.11049604451669623
mel_mean46 -0.11018388309697262
mel_mean54 -0.10984499957766858
mel_mean57 -0.10980907830930814
chroma_mean10 -0.1097088614968689
mel_mean2 -0.10945398743527775
mel_mean8 -0.10879796747332725
mel_mean56 -0.10824800488976036
mel_mean48 -0.10784943958989111
mel_mean93 -0.10682123859462057
mel_mean45 -0.10592731266660911
mfcc_mean0 -0.10552389200664937
mel_mean62 -0.10521365518382228
mel_mean92 -0.1049576270648691
chroma_std4 0.10438276963921167
mel_mean61 -0.10419527230689987
mel_mean53 -0.10412258518760101
mel_std38 -0.10399365626641222
mel_mean112 -0.10381865259141819
mel_std93 -0.10380351298634516
mel_mean40 -0.10369339920953248
mel_mean37 -0.10360708157321576
mel_mean47 -0.10335855606008303
chroma_std0 -0.10318863221022957
mel_mean91 -0.10311195644182156
mel_mean44 -0.10306667571893637
mel_std55 -0.10268614626425063
mel_std91 -0.1026332532014582
mel_std92 -0.10248191386722212
mel_mean105 -0.10140438061862662
mel_std49 -0.10071510383057995
mel_std103 -0.10006523637529241
mel_std44 -0.09982224318628727
chroma_mean6 0.09977178646681469
zcr_mean -0.0994838528538901
chroma_std8 -0.09887349102462953
mfcc_mean8 -0.09883710480578838
mel_std105 -0.09850058118583362
chroma_mean8 -0.09840849579252108
mfcc_mean3 0.09831658424759318
mel_std60 -0.09807838483532264
mel_mean42 -0.09756597350284334
mel_mean103 -0.09746123170053374
mel_std5 0.09744116885716307
mel_std58 -0.09718224942996848
mel_mean41 -0.09697155628446023
mel_std6 0.09696992506876582
mel_std46 -0.09695504192088436
mel_std54 -0.0966838754298254
mel_mean50 -0.09663106497583987
mel_mean11 0.09639828322174107
mel_mean94 -0.09612170030547763
mel_std90 -0.0956063878010188
mel_mean83 -0.09535308577269322
mel_mean63 -0.09529876000193639
mel_std112 -0.09518897043163518
mel_mean90 -0.09459111200160954
mel_mean33 -0.09448043469487599
mel_std42 -0.09418706616223792
mfcc_std0 -0.09416506016245425
mel_std57 -0.09377707248876967
mel_std37 -0.09373505543024056
std_pause_duration -0.09372865866494325
mel_std40 -0.09359627140168562
mel_std45 -0.09316348879421911
chroma_std5 0.09313713411888429
mel_mean9 -0.09306033998561863
mfcc_max3 0.09231026322942996
mel_std94 -0.09222677890203837
mel_mean52 -0.09222084586354896
mel_mean84 -0.0921627780371364
mfcc_min8 -0.09187156103237945
mel_std59 -0.09149205124162363
chroma_mean3 0.0912486191162714
mel_mean106 -0.09120119056440688
mfcc_max9 -0.0911137682532986
mel_std48 -0.09040456794718243
mel_mean51 -0.09011279980605708
mel_mean43 -0.09003951223169912
mel_mean104 -0.08989226758175717
mel_mean15 0.08954697509859862
mel_std56 -0.08920209196057276
rms_mean -0.08885932829327908
mel_std41 -0.0879342428164928
mel_mean86 -0.08786296127987847
mel_std89 -0.0878288672690079
mel_mean95 -0.08775527638470224
mel_mean111 -0.08768746934984667
mel_std53 -0.0874353448052612
mel_std47 -0.08739259289824088
mel_std62 -0.08734062209496427
mel_std43 -0.08694172882580196
mel_std106 -0.08676783482134835
mel_mean87 -0.08646713136643813
mel_std104 -0.08555583046369833
mel_mean89 -0.08512859744190114
mel_std102 -0.08506147963574788
mel_mean85 -0.08472468353002709
mel_std83 -0.08465602821369174
mel_std33 -0.08442079532066589
mel_std95 -0.08404258512918363
mel_mean102 -0.08388412289127135
mel_std100 -0.08364611212299268
mel_mean109 -0.08317720480756664
chroma_mean11 -0.08292960155394972
mel_mean64 -0.08291096402073984
mel_std87 -0.08285657783458694
mel_mean88 -0.08251853889786089
mfcc_max1 0.08249416256932629
mel_mean107 -0.08210319168051879
mel_std61 -0.08196538909390848
mel_std16 0.08157352373816878
mel_std88 -0.08132593158125728
mel_mean100 -0.08116421929340288
mel_std111 -0.08106219741688456
mel_mean108 -0.08058815849169275
mel_mean110 -0.08023540409063355
chroma_mean0 -0.08017962285141213
mel_mean82 -0.07975184295923772
mel_std101 -0.07945492964570665
mel_std11 0.0793143454849417
mel_mean96 -0.07878985230621184
mel_std84 -0.07828570801925862
tonnetz_mean3 -0.07801689402974533
mel_mean32 -0.07798662345037013
mel_std3 -0.07766971140776628
mfcc_max8 -0.07753594128836873
mel_mean101 -0.07732940381126872
mel_std109 -0.07725873136048433
mel_std63 -0.07692641832374682
mfcc_min4 -0.07660873197769921
mel_std108 -0.07633877995939838
mel_std107 -0.07631676779477839
mel_std86 -0.07612673301583084
mel_mean99 -0.07585975984644737
mel_std96 -0.0749447748375134
mel_mean97 -0.07437915110371948
mfcc_max10 0.07368091993628605
mel_std50 -0.07327665889873555
mel_std82 -0.0726588066715062
f3 -0.0726118786548729
mel_std110 -0.07195909404851057
mel_std97 -0.0714883385151511
mel_std99 -0.07137080467744508
mel_mean65 -0.07131682783642486
mel_mean75 -0.07126147253799998
mel_std85 -0.07082772698309783
mel_mean98 -0.07058819596617878
mel_std51 -0.07044224223296551
formant_energy_ratio -0.06952944065791607
chroma_std6 0.0689572983773264
mel_std32 -0.06890141290297666
mel_std52 -0.06801335343322218
chroma_std9 -0.06725521172440473
mfcc_mean2 -0.06698666898769022
mel_std75 -0.06565326420698446
mel_std98 -0.06562210095930786
zcr_min 0.06462789037961121
mel_mean31 -0.06425504480298044
mfcc_max11 -0.06397169412938775
mel_mean81 -0.06368215272714682
mel_mean74 -0.06360231316473136
mel_std64 -0.0629080847801399
mel_mean3 -0.06253531315549891
mel_mean21 0.06238800809016088
mel_mean80 -0.06192825555669325
mfcc_std9 0.061761726065726184
mfcc_min3 0.061681124010030515
chroma_mean2 0.06088879263840479
mfcc_max12 0.059740467341200004
mel_std81 -0.058921218541656536
tonnetz_std5 -0.057378537294832464
mel_mean79 -0.05646042548090906
chroma_std3 0.056341364031467875
f1 -0.05628396690453983
mel_std80 -0.056205310990700814
f2 -0.05609399747285743
mel_mean76 -0.05566939560320829
mel_mean66 -0.055574490413755825
mel_mean20 0.05515684617839507
mel_std21 0.055067633598814926
f0_max -0.054379773977978586
mel_std23 0.05436684829429689
mel_std74 -0.05224437528681237
chroma_std1 -0.05187473666395432
mfcc_max5 0.051859076714737384
tonnetz_std4 -0.0517009979814192
mel_std22 0.05146823595479668
mel_mean30 -0.0507829946686153
mel_mean22 0.05056949405663981
mel_std9 -0.05047520904972271
mel_std65 -0.05024362080793849
mel_std8 -0.04944191466667169
mel_mean77 -0.049053398050029506
mel_std79 -0.04893916856459938
mel_mean73 -0.048829011570052566
mel_mean67 -0.04852422452755363
mel_std76 -0.048522743733865815
mel_mean78 -0.04847251881223945
mfcc_std10 -0.048211462652770924
f0_min -0.04778662912610172
mfcc_mean10 0.047404035543384654
mel_std17 0.04721017363403995
mel_mean16 0.04685742416484982
mel_std31 -0.046514500211811416
mel_mean23 0.04630992011801358
tonnetz_std2 -0.046228816764149326
mel_std20 0.04477903466903411
tonnetz_mean1 -0.04443686405899592
mel_std24 0.04234128206760741
mel_std30 -0.04229589037766817
tonnetz_std3 -0.04227703337628475
tempo 0.04173894797264738
mel_std78 -0.04032217487096237
mel_std77 -0.040104896471986826
mel_mean24 0.03922449863612384
mel_std73 -0.0382782887311499
mel_mean68 -0.03658319546856735
mfcc_min7 -0.035649675262706675
mel_std66 -0.03546834153376323
mel_mean70 -0.034746308525736104
mel_mean72 -0.03467798855509212
mel_mean19 0.034356893054550905
mel_std19 0.03293500314495261
mel_mean69 -0.03224409884011332
rms_max 0.03166174250753724
mel_mean71 -0.03089121564252151
mel_mean7 -0.030173784046930014
b1 0.029651224160875
mfcc_min10 0.027595115616543518
mfcc_min12 -0.026499904083271974
mel_std18 0.026479249415613082
mfcc_std3 0.024885603482133024
tonnetz_std1 -0.02466995625881482
mfcc_max7 0.024606807374294444
mel_std67 -0.024140084876865753
mfcc_min2 -0.02353215557020222
mel_mean17 0.022692117709567746
mel_std27 0.022430013527922163
mel_std70 -0.022418426101545718
mfcc_min0 0.022323312568129427
tonnetz_std0 -0.021498397023521926
mel_mean27 0.021493117457684095
mel_mean18 0.021143382593462087
mfcc_std4 0.020739975431134833
mfcc_mean7 -0.020083812444981346
mel_std72 -0.019897210246905474
mel_std28 0.01939165544539866
mel_mean28 0.019302922490085424
mel_std69 -0.019085218692696308
mel_mean4 0.017918708361268684
tonnetz_mean4 -0.017792055497654998
mel_mean26 0.017510719492576793
chroma_std11 -0.017493062179120795
b2 -0.016861041914248386
mel_std71 -0.016760265334669865
b3 0.016181688661111124
mfcc_std11 0.016105511640024422
chroma_std10 -0.015629589963893985
mel_std68 -0.01548313564597026
mfcc_std7 0.01521537337753584
chroma_std7 0.015037448803085999
mel_std26 0.01481412637386059
mel_std4 0.014740534256587659
rms_std 0.013969310765066002
tonnetz_mean2 0.013109562689699253
chroma_mean7 0.012735579058234687
rms_min -0.012022003575177218
mel_std10 0.011526198454929104
mel_mean25 0.011195944473527685
tonnetz_mean0 -0.008655769281220851
mel_std7 0.00791769781357767
mel_mean10 0.007624898911816995
mfcc_min5 -0.006463809937462925
mfcc_std12 -0.006118354702625113
mfcc_mean12 0.006034078923982537
mel_std25 0.00522734597516766
tonnetz_mean5 -0.0048496671408035175
chroma_mean1 0.0027694738138760006
mfcc_std8 -0.0027395238059902505
mfcc_mean5 0.0023807327971912067
mel_std29 0.002142533384920659
mfcc_std5 0.0020771491307449833
mel_mean29 -0.0017435957289367358
chroma_std2 0.0003888396540661639

In [ ]:
data

,zcr_mean,zcr_std,zcr_max,zcr_min,rms_mean,rms_std,rms_max,rms_min,mfcc_mean0,mfcc_mean1,...,mel_std119,mel_std120,mel_std121,mel_std122,mel_std123,mel_std124,mel_std125,mel_std126,mel_std127,age
1.wav,0.210093,0.174175,0.786621,0.019043,0.031842,0.035200,0.200347,0.000241,-369.445770,55.719803,...,3.800879e-02,2.803914e-02,2.274095e-02,2.691475e-02,2.016690e-02,1.525524e-02,9.101027e-03,3.658939e-03,3.165333e-04,24.0
2.wav,0.078849,0.074397,0.397461,0.008789,0.069174,0.055064,0.238681,0.003501,-291.229675,122.431274,...,1.008640e-03,8.167035e-04,8.310446e-04,1.040648e-03,1.315697e-03,1.215531e-03,1.279807e-03,8.888561e-04,5.950056e-05,22.5
3.wav,0.105365,0.120708,0.574219,0.003418,0.044096,0.032049,0.186966,0.004962,-304.470520,72.080658,...,2.357865e-02,1.842017e-02,1.756822e-02,1.664084e-02,9.081427e-03,9.565935e-03,9.624348e-03,6.201901e-03,6.023237e-04,22.0
4.wav,0.173701,0.167091,0.799805,0.000000,0.121360,0.087285,0.379289,0.000018,-254.585403,38.093533,...,5.876975e-01,1.143306e+00,1.709680e+00,1.085319e+00,7.186143e-01,5.942925e-01,6.352082e-01,1.906777e-01,1.844911e-02,22.0
5.wav,0.107279,0.105950,0.498047,0.005371,0.059892,0.042143,0.183311,0.001987,-273.523865,112.785225,...,6.021491e-03,4.164151e-03,4.537857e-03,4.062913e-03,3.183328e-03,2.668071e-03,2.939539e-03,1.538673e-03,1.633528e-04,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2924.wav,0.077740,0.103368,0.635742,0.006836,0.077101,0.057661,0.358437,0.011932,-276.933838,135.242386,...,8.016796e-02,7.473018e-02,5.930423e-02,7.320457e-02,8.508126e-02,2.014178e-01,1.338326e-01,5.994967e-02,3.632866e-03,27.0
2926.wav,0.135405,0.113255,0.576172,0.020020,0.041325,0.040323,0.240033,0.000111,-332.338348,98.117645,...,2.269334e-10,1.972600e-10,1.760291e-10,1.601321e-10,1.481141e-10,1.391611e-10,1.325423e-10,1.280395e-10,1.253108e-10,22.0
2928.wav,0.111901,0.116163,0.545898,0.018555,0.074255,0.050410,0.212878,0.009050,-227.502090,128.541199,...,1.128745e-06,9.457501e-07,8.026810e-07,6.774349e-07,5.949678e-07,5.345842e-07,4.376668e-07,3.377193e-07,9.540887e-08,39.0
2929.wav,0.111799,0.103551,0.485352,0.015625,0.035550,0.024755,0.132884,0.000972,-303.633423,100.347366,...,5.534558e-03,5.022744e-03,4.600589e-03,3.465061e-03,1.789898e-03,9.638647e-04,7.318112e-04,3.234728e-04,2.300417e-05,24.0
2932.wav,0.115139,0.100257,0.459473,0.016113,0.050893,0.043128,0.216863,0.000012,-332.118744,109.372849,...,1.982043e-08,1.874660e-08,1.820587e-08,1.662396e-08,1.512277e-08,1.541225e-08,1.342520e-08,7.743902e-09,7.438620e-10,18.0

In [22]:
for col, impor in sorted(zip(data.drop(columns='age').columns, RandomForestRegressor(n_jobs=-1).fit(data.drop(columns=['age']), data['age']).feature_importances_), key=lambda x: x[1], reverse=True):
    print(col, impor)

#pauses 0.033291510847527565
mel_mean120 0.01031548831471162
mfcc_max4 0.008594678722657411
mel_std0 0.00854069813127445
mfcc_min6 0.008499285789015576
mel_mean5 0.00846672644185032
mel_std121 0.008241359381554472
chroma_mean5 0.008219656004701035
mel_std5 0.008105401993691287
mfcc_max9 0.007764648835436157
b1 0.007555981426813023
spectralContrast_std 0.007307006147323889
mfcc_mean7 0.007225309094851698
chroma_mean4 0.007201598085615537
mel_mean118 0.006186216292772341
mfcc_std6 0.006097819815572396
mfcc_std5 0.00607917201233716
chroma_mean3 0.006006382610319715
mel_mean121 0.005960223322191126
mel_mean12 0.005815787895757613
mel_std13 0.005780861241803097
mel_mean8 0.005717241804324016
chroma_std4 0.005708619584976865
mel_mean0 0.005665318786000502
mfcc_std9 0.005657960990728189
mfcc_mean6 0.005497970506686972
mel_mean126 0.005484370766743126
mfcc_max2 0.005480369485119724
mfcc_min9 0.005331850707959049
mfcc_min11 0.005301968704024249
chroma_mean6 0.00529294410461991
tonnetz_mean3 0.005143100645049119
mel_mean13 0.0051054411036727445
mfcc_mean9 0.005058014074232295
mel_mean2 0.0049305486291687985
speech_rate 0.004855887869794753
mfcc_max7 0.004783389852674057
mfcc_min8 0.00474800698252453
mel_std1 0.004618362878977753
b3 0.004551316170538898
mfcc_min3 0.004533130910414067
mel_std118 0.004514003269047026
std_pause_duration 0.0044890731442249
chroma_mean8 0.004484285491120056
mel_std34 0.0044347129447541486
chroma_mean2 0.004421820117639184
mfcc_mean10 0.004421374147770657
b2 0.004417725302436569
mfcc_min7 0.004378414353897972
spectralBandwidth_std 0.004349706684480249
chroma_mean9 0.004343767339432527
mfcc_mean4 0.004259941632132907
mfcc_std2 0.004251765656017121
f0_std 0.004232191505018637
mel_mean45 0.0042001033749597795
mel_std125 0.004190737868824955
mfcc_max5 0.0041600702463222726
mel_mean119 0.004153892599851107
f1 0.004152041876319852
mfcc_max10 0.004133833774740674
chroma_std7 0.004116486647087934
chroma_std5 0.004034286226602835
mfcc_max6 0.004032250323434906
spectralContrast_mean 0.0040260899188079005
mel_std50 0.004008635003304041
mfcc_std4 0.003978869081519043
mfcc_std8 0.003911288178362506
chroma_std3 0.003737264435711954
tonnetz_std1 0.003720921160426981
mfcc_min10 0.0037084924789234897
mel_std14 0.0036880658102100092
mfcc_mean2 0.003651818113079692
mfcc_min0 0.0036247105028210116
chroma_mean7 0.0036189977556376676
mel_mean11 0.0036065216700652256
mfcc_min4 0.003605496828149337
tonnetz_mean2 0.0035983266709024198
chroma_std8 0.003582227281773126
chroma_std10 0.003503390316273583
mel_std15 0.003493327029777985
mfcc_min12 0.0034738957538659543
mel_mean117 0.003454835422130713
mfcc_max1 0.0033937998035799243
mel_std10 0.003385022093071425
mfcc_max8 0.0033685866285546543
chroma_std6 0.003366209180891326
mfcc_std11 0.0033534744958895017
mel_mean9 0.003348442048020433
chroma_mean10 0.0033407313652551677
mfcc_std7 0.0033320418152684834
mel_std12 0.0032863502546385116
mfcc_max11 0.0032832708920442007
f3 0.003280205077376118
mel_mean47 0.0032697449595733047
mel_std127 0.003188571813356454
f2 0.0031699687465041025
tonnetz_mean4 0.003155556892182063
tonnetz_std0 0.003144639819410071
tonnetz_mean1 0.0031417701206948676
chroma_std0 0.0031203028934335226
chroma_std2 0.003094299102648082
mfcc_mean11 0.0030775668445490907
tonnetz_std5 0.003068225216669492
mel_std6 0.0030484940808938672
mel_mean127 0.003046103730419348
chroma_std11 0.003041226454973059
tonnetz_std2 0.0030221456440991464
chroma_std1 0.0030094927729158675
mel_mean6 0.003008309124113118
mel_std3 0.003000889682222857
mel_std4 0.0029421272113131745
mel_std83 0.002922127050503677
mfcc_min5 0.0029065408234114094
mel_mean53 0.002900289127164302
mel_mean3 0.002897592417983385
tonnetz_mean5 0.0028886717041927716
chroma_std9 0.002852042835600447
mel_std8 0.002850901631528848
mel_std2 0.0028367294283010965
mel_mean123 0.002827384447796185
formant_energy_ratio 0.002824262729184179
tonnetz_mean0 0.002818661395911937
chroma_mean0 0.002818190050491411
tonnetz_std3 0.0028015243002510537
mfcc_std12 0.002771463842560832
mfcc_max0 0.002770480767512855
mfcc_max12 0.002762237657428422
mel_mean44 0.0027615815854767317
mel_std22 0.002736717630430057
mel_mean14 0.0027294314815780748
mfcc_min2 0.0027268513835147982
mel_std36 0.0027227942880862633
mel_std7 0.0026816350765760614
mel_std16 0.00267029974961071
mfcc_mean12 0.0026698965026408926
zcr_min 0.002657687486860746
mel_mean10 0.0026522221314219923
mfcc_std3 0.0026465854733307955
mel_mean29 0.0026294179277077663
mel_std29 0.002602056709978936
f0_mean 0.002572026294424351
mean_pause_duration 0.002568589534796294
mel_std56 0.0025671195207240764
chroma_mean1 0.0025582090129767985
mfcc_mean1 0.0025313232108684874
mfcc_mean5 0.0025237171109598173
rms_min 0.0025196046961772993
mel_std124 0.0025179161015826367
mel_mean46 0.0025084466389954175
mel_std30 0.00250020458699994
chroma_mean11 0.0024916023977612427
mel_mean41 0.0024464165721792656
rms_max 0.002445823328513095
mfcc_std10 0.0024287828569906173
mfcc_max3 0.0024275201251676352
mel_std42 0.00242699704507214
mfcc_mean8 0.0024234304689721067
mel_std122 0.0024232504274619886
mel_mean49 0.0024064380152904285
spectralCentroid_std 0.0023988671409964986
mel_std11 0.0023826765501442737
mel_std18 0.0023755894359803803
mel_std45 0.0023752116747721196
mel_mean24 0.0023538305925721024
mel_std55 0.002338562972490363
tempo 0.0023337825365651503
mel_mean33 0.0023181048560022978
mfcc_mean3 0.002265780901022261
mel_mean59 0.0022582196828503593
mel_std23 0.0022539337389768117
mel_std20 0.0022476099233312815
mel_std25 0.002244966429238696
mel_std63 0.0022288028248554923
mel_std24 0.0022248752157547104
mel_std35 0.0022174350763816465
mel_std32 0.0022004622425683424
mel_std120 0.002195067550829467
spectralRolloff_mean 0.0021866557657718414
mel_std67 0.0021694778418835502
mel_mean36 0.0021669528343730387
mel_mean7 0.002164938277469556
mel_std26 0.0021581717767644036
mel_mean15 0.002152745649597746
mel_mean43 0.0021386283073290433
mel_std57 0.002133753987946943
mel_mean17 0.002111087520824687
mfcc_std0 0.0021037010828983214
mel_mean84 0.0020752740560038485
mel_mean1 0.002074277171271008
mel_std75 0.002073142018973882
mel_mean4 0.0020649767686318717
mel_std99 0.002058542964421315
mel_std51 0.002054670245773902
tonnetz_std4 0.002052741749035602
mel_std31 0.0020389759726608934
mfcc_min1 0.002030452279117229
mel_mean30 0.0020227345212439365
mel_mean42 0.0020163657157697334
mel_std54 0.0020117088343752122
mel_mean38 0.002008713183273852
mel_std58 0.001993546364683091
mel_std28 0.0019879665270834306
mel_std59 0.001979971942075374
mel_mean18 0.001979659484482177
mel_std61 0.001975265322067493
mel_mean68 0.0019518289773833434
zcr_max 0.0019495832762807636
mel_mean50 0.0019253476016284675
mel_std9 0.0019141307086773063
mel_std33 0.0019097254082978208
mel_mean113 0.0018957600524821914
mel_std53 0.001895632562493172
mel_std82 0.0018953674754689312
mel_std69 0.0018684920237224106
mel_mean56 0.0018349826020990815
mel_std46 0.0018273586645570724
spectralRolloff_std 0.0018265103555946246
mel_std126 0.0018197906861492892
mel_std49 0.001812485829966641
mel_std41 0.0018108410616083025
spectralBandwidth_mean 0.001797746817895754
mel_std39 0.0017961486493785596
mel_std44 0.001792650318517497
mel_mean28 0.001787266536413649
mel_mean35 0.0017821666967998556
mel_std43 0.0017754703982256633
mel_std65 0.0017751600163280507
mel_std68 0.0017748208428942194
mel_mean37 0.0017640290065252847
mel_std52 0.0017507332918184457
mel_mean79 0.001738520562510739
mel_mean20 0.0017122776547196536
mel_mean52 0.0017100540725977597
mel_mean21 0.001706967118345562
mel_std27 0.0017001734792002918
mel_mean27 0.0016770978004356301
mel_std73 0.0016732990288470975
mel_mean19 0.0016694939306502864
mel_mean31 0.0016684661227044726
mel_std88 0.0016665742022978442
mel_mean66 0.001654633504166026
mel_std112 0.0016392655458896362
mel_mean76 0.0016349103827905157
mel_mean125 0.001630901441993673
mel_std79 0.0016062657816657388
mel_std87 0.0016044695932569666
mel_std84 0.0016043179126514545
mel_std116 0.0015969038189198792
mel_std72 0.0015958847681122584
mel_std123 0.001591276378563817
mel_mean51 0.0015863063949129836
mel_mean54 0.0015762877358804627
mel_std80 0.0015734865820139577
mel_mean80 0.0015608810164796435
mel_mean104 0.0015521411079466078
mel_std62 0.0015503579731605543
mel_std64 0.0015487246354228773
mel_mean58 0.001545314882470543
mel_mean16 0.0015442245806269017
zcr_mean 0.0015381826176174846
mel_mean23 0.0015346619007877529
mel_std77 0.00153061767834078
mel_std91 0.0015237502887146808
mel_std17 0.0015185158360820638
mel_std114 0.0015182414445034803
mfcc_mean0 0.001517952330999421
mel_mean25 0.001507573990607306
mel_std113 0.0015038583683169562
mel_std38 0.0015038238360655693
mel_mean60 0.001502276924487311
mel_mean71 0.001495676952839464
mel_mean83 0.00149308553751094
mel_mean105 0.0014776298020547484
mel_mean22 0.0014738175988798792
mel_std85 0.001472596417398859
mel_mean86 0.0014695970939300922
mel_mean93 0.0014616926194795914
mel_mean87 0.0014595165039178032
mel_mean88 0.0014404085096660325
mel_std71 0.0014311917603934809
mel_mean89 0.0014285312283079535
mel_std89 0.001425492875309722
mel_mean85 0.0014226529283487973
mel_mean55 0.0014215590287884475
mel_std106 0.0014151288301276477
mel_std103 0.001412780695815008
mel_std96 0.0014077696586544605
mel_mean26 0.001406527460421742
mel_std19 0.001403956565723895
mel_std98 0.001402542138584304
mel_std108 0.001397351178701482
mel_mean63 0.0013923975200129735
mel_std90 0.0013795009753884318
mel_mean34 0.0013667978642490852
mel_mean72 0.0013558007489464495
zcr_std 0.0013549847329557335
mel_std47 0.001352725211272766
mel_std48 0.0013523768877001998
mel_std105 0.0013495115622679968
mel_mean109 0.0013333466098333058
mel_mean92 0.0013284756566003947
mel_mean103 0.0013226416658707757
mel_std117 0.0013209800097466707
mel_mean96 0.0013116946424124726
mel_std76 0.0012925477077943325
mel_mean57 0.0012918663174670219
mfcc_std1 0.0012917000697688053
mel_mean81 0.0012868312869458822
mel_mean74 0.0012761910531246732
mel_mean82 0.0012702041833187808
mel_std21 0.001266113520703188
mel_std66 0.0012604621722769466
mel_mean116 0.0012599047012943607
mel_std95 0.001252260926860929
mel_std104 0.0012454451178795798
mel_mean95 0.001236285936513849
rms_mean 0.001234739703367074
mel_std107 0.0012320829028064952
mel_mean40 0.001229567119307692
mel_mean97 0.0012277945431976407
mel_std74 0.001224746198338705
mel_std110 0.001207585091990146
mel_mean115 0.0012061219853058856
mel_mean61 0.001205448756651445
mel_std119 0.001194623372026383
mel_mean32 0.0011921042209147822
mel_std40 0.0011799165632210725
mel_mean99 0.001174812688283125
mel_mean102 0.0011715760664303691
mel_std102 0.0011620593951335255
spectralCentroid_mean 0.001153338617036358
mel_std37 0.0011325207519940388
mel_std100 0.0011325165814134667
mel_mean62 0.0011061355581597997
mel_mean124 0.001102385032147734
mel_std115 0.0010997286456023597
mel_std101 0.001094010794729166
rms_std 0.0010836888520901519
mel_mean91 0.0010813821749705624
mel_std86 0.0010624755177651387
mel_mean98 0.001060563533501919
mel_mean77 0.0010574831731919956
mel_mean106 0.0010433707138320586
mel_std97 0.0010406426077048427
mel_mean108 0.001038545167897452
mel_mean39 0.001029982928268865
mel_mean73 0.0010200163632060047
mel_mean48 0.0010123382435236494
mel_mean64 0.0010019917637089646
mel_std60 0.000994756025645429
mel_mean111 0.0009828205767777858
mel_mean65 0.0009558617252235581
mel_mean107 0.0009531254281124079
mel_std70 0.0009530965957792244
mel_std111 0.0009526348080610352
mel_std93 0.0009494435706301241
mel_mean75 0.0009419523803779751
mel_mean100 0.0009379679290441806
mel_mean78 0.0009202712657213113
mel_mean69 0.0009121719506472263
mel_std92 0.0009077323017213095
mel_mean70 0.0009034572310640517
mel_mean67 0.000884741433630544
mel_mean112 0.0008706221353372291
mel_mean94 0.0008524196520993117
mel_std81 0.0008492682180625187
mel_mean122 0.0008437437365357965
mel_std94 0.0007952527406626452
mel_std109 0.000775994123975569
mel_mean101 0.0007645823982109215
mel_std78 0.0007534408209225051
mel_mean114 0.0007115221890303972
mel_mean90 0.0006125699406076781
mel_mean110 0.0005658376912382333
f0_min 0.0005366615646689526
f0_max 8.136229574379036e-07

In [116]:
cross_val_score(RandomForestRegressor(n_jobs=-1), data.drop(columns=['age']), data['age'], cv=5, scoring='neg_mean_absolute_error').mean()

np.float64(-10.658920353982301)

In [24]:
from sklearn.pipeline import make_pipeline
from sklearn.neighbors import KNeighborsRegressor

cross_val_score(make_pipeline(StandardScaler(), KNeighborsRegressor(n_jobs=-1)), 
                data[[col for col in data.columns if 'mel' in col]], data['age'], cv=36, scoring='neg_mean_absolute_error').mean()

np.float64(-11.704707200551617)

In [265]:
cross_val_score(make_pipeline(StandardScaler(), RandomForestRegressor(n_jobs=-1)), 
                tempdata[tempdata['gender']==0][data.columns].drop(columns=['age']), 
                tempdata[tempdata['gender']==0]['age'], 
                cv=5, scoring='neg_mean_absolute_error').mean()

np.float64(-10.531425287356322)

In [38]:
beat = {file:np.concatenate(librosa.beat.beat_track(y=nonAfricanAudio[file], sr=22050, trim=True), axis=0)
                     for file in nonAfricanAudio}

In [79]:
minBeat =np.min([len(beat[file]) for file in beat])
normalizedBeat = pd.DataFrame({file:np.concatenate(([beat[file][0]], (  
                beat[file][1:]
                if beat[file].shape[0] == minBeat
                else [np.mean(beat[file][1+beat[file].shape[0]*i//minBeat:1+min(beat[file].shape[0], beat[file].shape[0]*(i+1)//minBeat)]) for i in range(0, minBeat-1)]
            )), axis=0)  for file in beat},
            index=[f'normBeat{i}' for i in range(0, minBeat)]).T

In [64]:
# Apply the chroma filterbank to the audio signal
chroma_filter = librosa.filters.chroma(sr=22050, n_fft=2048, n_chroma=12, octwidth=None)
filtered_audio = pd.DataFrame({file:np.dot(chroma_filter, nonAfricanAudio[file][:1025]) for file in nonAfricanAudio},
                               index=[f'chroma_filter{i}' for i in range(0,12)] ).T

In [84]:
data

,zcr_mean,zcr_std,zcr_max,zcr_min,rms_mean,rms_std,rms_max,rms_min,mfcc_mean0,mfcc_mean1,...,mel_std119,mel_std120,mel_std121,mel_std122,mel_std123,mel_std124,mel_std125,mel_std126,mel_std127,age
1.wav,0.210093,0.174175,0.786621,0.019043,0.031842,0.035200,0.200347,0.000241,-369.445770,55.719803,...,3.800879e-02,2.803914e-02,2.274095e-02,2.691475e-02,2.016690e-02,1.525524e-02,9.101027e-03,3.658939e-03,3.165333e-04,24.0
2.wav,0.078849,0.074397,0.397461,0.008789,0.069174,0.055064,0.238681,0.003501,-291.229675,122.431274,...,1.008640e-03,8.167035e-04,8.310446e-04,1.040648e-03,1.315697e-03,1.215531e-03,1.279807e-03,8.888561e-04,5.950056e-05,22.5
3.wav,0.105365,0.120708,0.574219,0.003418,0.044096,0.032049,0.186966,0.004962,-304.470520,72.080658,...,2.357865e-02,1.842017e-02,1.756822e-02,1.664084e-02,9.081427e-03,9.565935e-03,9.624348e-03,6.201901e-03,6.023237e-04,22.0
4.wav,0.173701,0.167091,0.799805,0.000000,0.121360,0.087285,0.379289,0.000018,-254.585403,38.093533,...,5.876975e-01,1.143306e+00,1.709680e+00,1.085319e+00,7.186143e-01,5.942925e-01,6.352082e-01,1.906777e-01,1.844911e-02,22.0
5.wav,0.107279,0.105950,0.498047,0.005371,0.059892,0.042143,0.183311,0.001987,-273.523865,112.785225,...,6.021491e-03,4.164151e-03,4.537857e-03,4.062913e-03,3.183328e-03,2.668071e-03,2.939539e-03,1.538673e-03,1.633528e-04,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2924.wav,0.077740,0.103368,0.635742,0.006836,0.077101,0.057661,0.358437,0.011932,-276.933838,135.242386,...,8.016796e-02,7.473018e-02,5.930423e-02,7.320457e-02,8.508126e-02,2.014178e-01,1.338326e-01,5.994967e-02,3.632866e-03,27.0
2926.wav,0.135405,0.113255,0.576172,0.020020,0.041325,0.040323,0.240033,0.000111,-332.338348,98.117645,...,2.269334e-10,1.972600e-10,1.760291e-10,1.601321e-10,1.481141e-10,1.391611e-10,1.325423e-10,1.280395e-10,1.253108e-10,22.0
2928.wav,0.111901,0.116163,0.545898,0.018555,0.074255,0.050410,0.212878,0.009050,-227.502090,128.541199,...,1.128745e-06,9.457501e-07,8.026810e-07,6.774349e-07,5.949678e-07,5.345842e-07,4.376668e-07,3.377193e-07,9.540887e-08,39.0
2929.wav,0.111799,0.103551,0.485352,0.015625,0.035550,0.024755,0.132884,0.000972,-303.633423,100.347366,...,5.534558e-03,5.022744e-03,4.600589e-03,3.465061e-03,1.789898e-03,9.638647e-04,7.318112e-04,3.234728e-04,2.300417e-05,24.0
2932.wav,0.115139,0.100257,0.459473,0.016113,0.050893,0.043128,0.216863,0.000012,-332.118744,109.372849,...,1.982043e-08,1.874660e-08,1.820587e-08,1.662396e-08,1.512277e-08,1.541225e-08,1.342520e-08,7.743902e-09,7.438620e-10,18.0

In [118]:
from sklearn.ensemble import HistGradientBoostingRegressor


cross_val_score(HistGradientBoostingRegressor(), pd.concat([
                                                            normalizedBeat, 
                                                            data.drop(columns=['age']),
                                                            
                                                            ], axis=1), data['age'], cv=10, scoring='neg_mean_absolute_error').mean()

np.float64(-9.803619501172014)

In [126]:
dev = pd.read_csv('./data/development.csv', header=0, index_col=0).drop(columns=['sampling_rate'])
dev['gender'] = dev['gender'].map(lambda x: 0 if x=='male' else 1)
dev['tempo'] = dev['tempo'].map(lambda x: float(x[1:-1]))

predict = pd.read_csv('./data/evaluation.csv', header=0, index_col=0).drop(columns=['sampling_rate'])
predict['gender'] = predict['gender'].map(lambda x: 0 if x=='male' else 1)
predict['tempo'] = predict['tempo'].map(lambda x: float(x[1:-1]))

In [135]:
cross_val_score(HistGradientBoostingRegressor(categorical_features=dev.drop(columns=['age', 'path']).dtypes=='object'), 
                dev.drop(columns=['age', 'path'])[dev['num_words']<60], 
                dev[dev['num_words']<40]['age'], cv=10, scoring='neg_mean_absolute_error').mean()

np.float64(-3.228220422809062)

In [138]:
predictAfrican = pd.Series(HistGradientBoostingRegressor(categorical_features=dev.drop(columns=['age', 'path']).dtypes=='object')
                  .fit(dev.drop(columns=['age', 'path'])[dev['num_words']<60], dev[dev['num_words']<60]['age'])
                  .predict(predict.drop(columns=['path'])[predict['num_words']<60]),
                  name='Predicted',
                  index=predict[predict['num_words']<60].index)

In [ ]:
predictNonAfrican = pd.read_csv('./data/predicted.csv', header=0, index_col=0)
predictNonAfrican = pd.Series(predictNonAfrican.values[:, 0], index=predictNonAfrican.index, name='Predicted')